language: python
python:
    - "3.5.2"
#command to install independencies
install:
    - pip install -r requirements.txt
    - pip install coveralls

#command to run tests
script: 
    - nosetests tests/test_users.py
after_success:
    - coveralls

